services:
  - type: web
    name: n8n-flowbot
    env: docker
    # No incluyas `dockerCommand` ni `image` aquí; Render usará tu Dockerfile
    environment:
      DATABASE_TYPE: "postgresdb"
      DATABASE_URL:  "postgres://TU_USUARIO:TU_PASS@TU_HOST_NEON:5432/TU_BD"
      N8N_LOCAL_FILES_ROOT: "/home/node/.n8n"
      PORT: "8080"
