services:
  - type: web
    name: n8n-flowbot
    env: docker
    # Render debería usar la imagen especificada en el Dockerfile o que configures en la UI
    # image: n8nio/n8n:latest # Si hay campo para imagen, especifica aquí
    # Si no hay campo de imagen, Render usa la del Dockerfile.
    # En este caso, DEJAMOS EL START COMMAND VACÍO EN RENDER.
    # El CMD del Dockerfile debería ser suficiente.
    # dockerCommand: "" # Dejar vacío
    environment:
      N8N_DATABASE_MODE: postgres
      DATABASE_URL: "postgres://TU_USUARIO_NEON:TU_CONTRASENA_NEON@TU_HOST_NEON:5432/TU_NOMBRE_BD_NEON"
      N8N_LOCAL_HOME: "/home/node/.n8n"
      # Estas variables son las que n8n usará INTERNAMENTE para saber su puerto.
      N8N_PORT: "8080"
      N8N_WEBSERVER_PORT: "8080"
      # Esta variable la usa Render para el tráfico externo y la pasa a la aplicación.
      PORT: "8080"
      GENNARO_LISTEN_PORT: "8080"
