services:
  - type: web
    name: n8n-flowbot
    env: docker
    plan: free
    region: oregon
    environment:
      DATABASE_TYPE: postgresdb
      DATABASE_URL: "postgres://TU_USUARIO:TUPASS@TU_HOST_NEON:5432/TU_BD"
      N8N_LOCAL_FILES_ROOT: "/home/node/.n8n"
      PORT: "8080"
