services:
  - type: web
    name: n8n-flowbot # El nombre que le darás a tu servicio en Render
    env: docker
    dockerCommand: "npx n8n --host 0.0.0.0 --port $PORT --no- கருtype-check"
    environment:
      N8N_DATABASE_MODE: postgres
      DATABASE_URL: postgresql://neondb_owner:npg_kX5tpy4COEJQ@ep-lucky-scene-a8tiogev-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require' # <-- ¡REEMPLAZA ESTO CON TU URL DE NEON!
      N8N_LOCAL_HOME: "/home/node/.n8n"
      # Las siguientes son opcionales para el primer despliegue manual en Render,
      # pero son buenas prácticas para un despliegue automatizado posterior.
      # Si no estás seguro de la URL que te dará Render, puedes omitirlas por ahora
      # y configurarlas manualmente en la UI de Render.
      # N8N_HOST: "tu-nuevo-nombre-en-render.onrender.com" # <-- ¡REEMPLAZAR CON LA URL ASIGNADA POR RENDER!
      # N8N_PORT: $PORT
      # N8N_WEBSERVER_PORT: $PORT
